<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_walker">

    <!-- Define properties for specifying the overall mass distribution of the robot -->
    <xacro:property name="masstotal" value="1" />
    <xacro:property name="massbodytolegratio" value="0.5" />
    <xacro:property name="massbody" value="${masstotal / (1 + 2 / massbodytolegratio)}" />

    <xacro:property name="bodywidth" value="0.3" />
    <xacro:property name="bodyheight" value="0.3" />
    <xacro:property name="bodydepth" value="0.3" />

    <!-- Define the upper portion of the robot -->
    <link name="body">
        <visual>
            <geometry>
                <box size="${bodywidth} ${bodyheight} ${bodydepth}">
                </box>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${bodywidth} ${bodyheight} ${bodydepth}">
                </box>
            </geometry>
        </collision>
        <inertial>
            <mass value="${massbody}" />
            <inertia 
                ixx="${1/12 * massbody * (bodyheight*bodyheight + bodydepth*bodydepth)}" 
                iyy="${1/12 * massbody * (bodywidth*bodywidth + bodydepth*bodydepth)}" 
                izz="${1/12 * massbody * (bodyheight*bodyheight + bodywidth*bodywidth)}" 
                ixy="0" 
                ixz="0" 
                iyz="0" />
        </inertial>
    </link>

    <!-- Include components -->
    <xacro:include filename="$(find walker_description)/urdf/walker_leg.macro.xacro" />

    <!-- Instantiate the left leg of the robot -->
    <xacro:walker_leg_macro id="left" />
    <joint name="body_to_leg_left" type="revolute">
        <parent link="body" />
        <child link="thigh_left" />
        <origin xyz="0 ${-bodyheight} ${-(bodydepth / 2 + shank_length)}" />
        <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    </joint>

    <!-- Instantiate the right leg of the robot -->
    <xacro:walker_leg_macro id="right" />
    <joint name="body_to_leg_right" type="revolute">
        <parent link="body" />
        <child link="thigh_right" />
        <origin xyz="0 ${bodyheight} ${-(bodydepth / 2 + shank_length)}" />
        <limit effort="100" lower="-0.5" upper="0.5" velocity="10"/>
    </joint>

    <!-- Include hardware configuration for ros2_control -->
    <xacro:include filename="$(find walker_description)/urdf/ros2_control/simple_walker.ros2_control.xacro" />
    <xacro:walker_ros2_control name="walker" plugin="gazebo_ros2_control/GazeboSystem" />

    <!-- Specify the Gazebo plugin for interfacing with ros2_control -->
    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <parameters>$(find walker_description)/config/ros2_controllers.yaml</parameters>

            <robot_param>robot_description</robot_param>
            <robot_param_node>robot_state_publisher</robot_param_node>
        </plugin>
    </gazebo>
</robot>