<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="walker_leg_macro">

    <xacro:property name="thigh_length" value="0.5" />
    <xacro:property name="shank_length" value="0.4" />
    <xacro:property name="knee_joint_radius" value="0.025" />
    <xacro:property name="ankle_joint_radius" value="0.025" />
    <xacro:property name="foot_length" value="0.3" />
    <xacro:property name="foot_width" value="0.1" />
    <xacro:property name="foot_height" value="0.05" />

    <xacro:property name="thigh_mass" value="1" />
    <xacro:property name="shank_mass" value="1" />
    <xacro:property name="foot_mass" value="1.5" />

    <xacro:macro name="walker_leg_macro" params="id">
        <link name="thigh_${id}">
            <visual>
                <geometry>
                    <cylinder length="${thigh_length}" radius="0.06"/>
                </geometry>
                <material name="white"/> 
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${thigh_length}" radius="0.06"/>
                </geometry>
            </collision>
            <inertial>
            <mass value="${thigh_mass}"/>
            <inertia 
                ixx="1e-3" 
                ixy="0" 
                ixz="0" 
                iyy="1e-3" 
                iyz="0" 
                izz="1e-3"/>
        </inertial>
        </link>

        <link name="shank_${id}">
            <visual>
                <geometry>
                    <cylinder length="${shank_length}" radius="0.06"/>
                </geometry>
                <material name="white"/> 
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${shank_length}" radius="0.06"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </collision>
            <inertial>
                <mass value="${shank_mass}"/>
                <inertia 
                ixx="1e-3" 
                ixy="0" 
                ixz="0" 
                iyy="1e-3" 
                iyz="0" 
                izz="1e-3"/>
                <origin rpy="0 0 0" xyz="0 0 ${-shank_length/2-knee_joint_radius}"/>
            </inertial>
        </link>

        <joint name="knee_joint_${id}" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2-knee_joint_radius}"/>
            <parent link="thigh_${id}"/>
            <child link="shank_${id}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" lower="0.0" upper="2.5" velocity="10"/>
        </joint>

        <link name="foot_${id}">
            <contact>
                <lateral_friction value="100"/>
            </contact>

            <visual>
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
                <material name="white"/> 
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </collision>
            <inertial>
                <mass value="${foot_mass}"/>
                <inertia 
                ixx="1e-3" 
                ixy="0" 
                ixz="0" 
                iyy="1e-3" 
                iyz="0" 
                izz="1e-3"/>
                <origin xyz="${(foot_length/2-0.05)} 0 ${-ankle_joint_radius-foot_height/2}"/>
            </inertial>
        </link>

        <joint name="ankle_joint_${id}" type="revolute">
            <origin rpy="0 0 0" xyz="0 0 ${-(knee_joint_radius + shank_length + ankle_joint_radius)}"/>
            <parent link="shank_${id}"/>
            <child link="foot_${id}"/>
            <axis xyz="0 1 0"/>
            <limit effort="100" lower="-0.1" upper="0.5" velocity="10"/>
        </joint>

    </xacro:macro>
</robot>