# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    # jetleg_controller:
    #   type: jetleg_controller/JetlegController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# jetleg_controller:
#   ros__parameters:
#     joints:
#       - knee_joint_
#     imus:
#       - imu0
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position