# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    jetleg_controller:
      type: jetleg_controller/JetlegController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

jetleg_controller:
  ros__parameters:
    joints:
      - knee_joint_
    imus:
      - imu0
    command_interfaces:
      - position
    state_interfaces:
      - position

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu0
    frame_id: shank_imu

# Generic implementation of joint trajectory controller, customize as needed, all values are placeholders
joint_trajectory_controller:
  ros__parameters:
    joints: 
      - knee_joint_

    command_interface:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03    
